# Generated by Django 5.2.3 on 2025-07-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('reg_no', models.CharField(max_length=30)),
                ('program', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
    ]
