# Generated by Django 5.2.3 on 2025-07-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('website', models.URLField()),
                ('faculty', models.CharField()),
                ('type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
