# Generated by Django 5.2.3 on 2025-07-03 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0003_daily_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='interns',
            name='university_id',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, related_name='interns', to='interns.universities'),
            preserve_default='true',
        ),
    ]
