# Generated by Django 5.2.3 on 2025-07-04 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0005_internshipday_remove_interns_university_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internshipday',
            options={'verbose_name': 'Internship Day', 'verbose_name_plural': ' Internship Day'},
        ),
        migrations.AlterModelOptions(
            name='universities',
            options={'verbose_name': 'University', 'verbose_name_plural': ' University'},
        ),
        migrations.AlterField(
            model_name='task',
            name='day',
            field=models.ForeignKey(blank='true', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='interns.internshipday'),
        ),
        migrations.AlterField(
            model_name='taskimage',
            name='task_image',
            field=models.ImageField(blank=True, null=True, upload_to='task_images/'),
        ),
    ]
